# Generated by Django 3.2 on 2021-04-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210424_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email2',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
