# Generated by Django 3.2 on 2021-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True, verbose_name='API Cache')),
                ('data', models.TextField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['query'],
            },
        ),
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, primary_key=True, serialize=False, verbose_name='claim type')),
                ('description', models.TextField(help_text='Enter a brief description of the claim type', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Collection name')),
                ('sports', models.TextField(max_length=1000)),
                ('field_names', models.TextField(max_length=1000)),
                ('field_types', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, primary_key=True, serialize=False, verbose_name='dealership name')),
                ('description', models.TextField(help_text='Enter a brief description of the dealership', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='service advisor name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer', max_length=30, primary_key=True, serialize=False, verbose_name='status')),
                ('description', models.TextField(help_text='Enter a brief description of the status', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, primary_key=True, serialize=False, verbose_name='submission type')),
                ('description', models.TextField(help_text='Enter a brief description of the submission type', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='technician name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
