# Generated by Django 3.2 on 2021-04-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, primary_key=True, serialize=False, verbose_name='claim type')),
                ('description', models.TextField(help_text='Enter a brief description of the claim type', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, primary_key=True, serialize=False, verbose_name='dealership name')),
                ('description', models.TextField(help_text='Enter a brief description of the dealership', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='service advisor name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer', max_length=30, primary_key=True, serialize=False, verbose_name='status')),
                ('description', models.TextField(help_text='Enter a brief description of the status', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionType',
            fields=[
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, primary_key=True, serialize=False, verbose_name='submission type')),
                ('description', models.TextField(help_text='Enter a brief description of the submission type', max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 30 characters or fewer.', max_length=30, verbose_name='technician name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_order', models.IntegerField(help_text='Enter Repair Order Number')),
                ('pdf', models.CharField(max_length=100, verbose_name='PDF file name')),
                ('upload_date', models.DateTimeField(null=True)),
                ('claim_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.claimtype', verbose_name='claim type')),
                ('dealership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dealership', verbose_name='dealership name')),
                ('service_advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serviceadvisor', verbose_name='service advisor name')),
                ('submission_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.submissiontype', verbose_name='submission type')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.technician', verbose_name='technician name')),
            ],
            options={
                'ordering': ['dealership', 'repair_order'],
            },
        ),
    ]
