# Generated by Django 3.2 on 2021-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='pdf',
            field=models.FileField(upload_to='pdf_folder'),
        ),
    ]
