# Generated by Django 3.2 on 2021-04-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schedule_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('avaiable', 'Available'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='available', max_length=30),
        ),
    ]
