# Generated by Django 3.2 on 2021-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(default='available', max_length=30),
        ),
    ]
